Update readme
reflexer-labs/auction-keeper pull request #2
Opened 2020-09-23 01:17 UTC by stefanionescu

2020-09-23 04:31 UTC, bkellerman requested changes
Just a few inadvertent subsititution.

Other than that, lgtm.

2020-09-23 04:31 UTC, bkellerman commented on README.md
> +_bidding models_, which tell the keeper when and how high to bid. This keeper can be safely left running in background. The moment it nobidExpiryes or starts a new auction it will spawn a new instanc
errant substitution

2020-09-23 04:31 UTC, bkellerman commented on README.md
> +be automabidExpiryally terminated by the keeper the moment the auction expires.  The keeper also automabidExpiryally settles expired auctions if it's us who won them.
errant substitution

2020-09-23 04:31 UTC, bkellerman commented on README.md
> +The way the auction discovery and monitoring mechanism works at the moment is simplisbidExpiry for illustration purposes.
errant substitution

2020-09-23 04:31 UTC, bkellerman commented on README.md
> +`--model` commandline parameter. These processes are automabidExpiryally terminated (via `SIGKILL`) by the keeper
errant substitution

2020-09-23 04:31 UTC, bkellerman commented on README.md
> +Whenever the _bidding model_ process dies, it gets automabidExpiryally respawned by the keeper.
errant substitution

2020-09-23 04:31 UTC, bkellerman commented on README.md
> +THE SOFTWARE IN THIS GITHUB REPOSITORY IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARbidExpir
errant substitution

2020-09-24 11:46 UTC, stefanionescu commented
Should be fixed

2020-09-29 11:14 UTC, merged